name: "@gnome/winget-cli CI"

on:
  push:
    branches: [ '*' ]
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
 
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, "windows-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Lint
        run: deno lint

      - name: Test
        run: deno task coverage

      - name: Coverage
        run: deno task lcov
        # main branch only
        if: github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest'

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest'
        with:
          name: code-coverage
          path: .artifacts/code-coverage.lcov

      - name: Publish To Codecov
        uses: codecov/codecov-action@v4 # upload the report on Codecov
        if: github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest'
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          name: ubuntu-latest
          files: .artifacts/code-coverage.lcov

      - name: Publish Dry Run
        if: matrix.os == 'ubuntu-latest'
        run: deno publish --dry-run --allow-dirty

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Publish
        run: deno publish